Small stability fixes
arbory/arbory pull request #232
Opened 2020-12-22 12:01 UTC by Gberzi01

Fix issues related to incomplete data configuration/setup

2020-12-22 19:53 UTC, exabyssus requested changes
Please see comments

2020-12-22 19:53 UTC, exabyssus commented on resources/assets/js/include/remote_validator.js
> +        let interval = setInterval(() => {
This seems like a hack on top of a hack. Could you rewrite this functionality properly to not use Interval?

2020-12-23 11:13 UTC, holystix commented on src/Providers/NodeServiceProvider.php
> +            if ($this->canReadSettings() && $this->isRouteCacheOutdated($path)) {
It's an edge case, but if routes are cached, and `settings` table doesn't exist, no artisan commands can be executed, not even to clear the routes cache.

2020-12-23 11:56 UTC, holystix commented on resources/assets/js/include/remote_validator.js
> +        let interval = setInterval(() => {
@Gberzi01 this can be simplified by removing the logic introduced in https://github.com/holystix/arbory/commit/d3003d45e23fd4c61791d7145bd6407575e977e9, and instead setting the `clicked_button` property on RemoveValidator instance before any validation or ajax events are triggered on the form. 

```
        jQuery('.main .primary .button[name=save], .main .primary .button[name=save_and_return]').click(event => {
            event.preventDefault();

            form.data('validator').clicked_button = jQuery(event.target);
            form.trigger('beforevalidation');

...
```

2020-12-23 12:50 UTC, Gberzi01 commented on src/Menu/Menu.php
> +        return (array) json_decode($menuCookie);
Added second parameter

2020-12-23 12:51 UTC, Gberzi01 commented on resources/assets/js/include/remote_validator.js
> +        let interval = setInterval(() => {
Fixed as suggested by @holystix

2020-12-28 09:14 UTC, merged