Fix remove relation key on file remove
arbory/arbory pull request #241
Opened 2021-02-22 10:16 UTC by Gberzi01

2021-02-23 10:30 UTC, holystix requested changes

2021-02-23 10:30 UTC, holystix commented on src/Admin/Form/Fields/ArboryFile.php
> +            $this->removeRelationKey($fileWasDeleted);
`removeRelationKey` method call could be moved to within `deleteCurrentFileIfExists` method, as it is tightly related to it anyway. This way, two things could be avoided:
1. Avoid mixing return types of `deleteCurrentFileIfExists`
2. Avod calling `removeRelationKey` when it might not be needed

For example
```
protected function deleteCurrentFileIfExists()
...

    $currentFile = $this->getValue();

    if (!$currentFile) {
        return;
    }

    if ($arboryFilesRepository->delete($currentFile->getKey())) {
        $this->removeRelationKey();
    }
```

2021-02-23 10:55 UTC, holystix approved these changes

2021-03-04 10:42 UTC, exabyssus approved these changes

2021-03-04 10:42 UTC, merged